### PR TITLE
Upgrade/angular v2.0.0 rc.5

### PR DESCRIPTION
**Pull request by platosha**
Connected to vaadin/angular2-polymer#67

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/angular2-polymer-quickstart/3)

### CODE REVIEW

**Comment by damianknopp** [comment]
Thanks for this update!

Is it just me? I had to call typings or I saw compile errors on npm start and npm run tsc

package.json
-    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
+    "start": "npm run postinstall && tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",

typings.json
-  "ambientDependencies": {
+  "globalDependencies": {

Errors without typings installed

> angular2-polymer-quickstart@1.0.0 start /Users/user/git/angular2-polymer-quickstart
> tsc && concurrently "npm run tsc:w" "npm run lite" 
> app/hero-detail.component.ts(35,42): error TS7006: Parameter 'hero' implicitly has an 'any' type.
> app/hero.service.ts(9,12): error TS2304: Cannot find name 'Promise'.
> app/hero.service.ts(13,12): error TS2304: Cannot find name 'Promise'.
> app/hero.service.ts(14,7): error TS7006: Parameter 'heroes' implicitly has an 'any' type.
> app/hero.service.ts(14,31): error TS7006: Parameter 'hero' implicitly has an 'any' type.
> app/heroes.component.ts(35,40): error TS7006: Parameter 'heroes' implicitly has an 'any' type.
> node_modules/@angular/common/src/directives/ng_class.d.ts(81,34): error TS2304: Cannot find name 'Set'.

macbook-pro:angular2-polymer-quickstart user$ node -v
v6.3.1
macbook-pro:angular2-polymer-quickstart user$ npm -v
3.10.3
macbook-pro:angular2-polymer-quickstart user$ tsc -v
Version 1.8.10

**Comment by tehapo** [comment]
Confirmed. I also get the same errors until I make the changes suggested by @damianknopp.

**Comment by platosha** [comment]
@damianknopp thank you for trying and reporting this!

Updated typings.json. It should be enough, because `npm install` also runs `postinstall` and hence `typings install`. Otherwise, it feels excessive to install typings on every start.

Verified by removing typings/\* node_modules/\* and running npm install, worked for me.

**Comment by tehapo** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/angular2-polymer-quickstart/3#-:-KPw7B_G9jPdg0AJ8xbM:bnfp4nl)_

**Pull request merged**
