### PR TITLE
Feature/mvp

### PR DESCRIPTION
**Pull request by platosha**
Resolves vaadin/components-team-tasks#152

This change is [Reviewable](https://reviewable.io/reviews/platosha/angular2-polymer-elements-quickstart/1)

### CODE REVIEW

**Comment by manolo** [comment]
Reviewed 3 of 15 files at r1.
Review status: 2 of 15 files reviewed at latest revision, 8 unresolved discussions.

---

_[bower.json, line 2 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZYREextGMkhWq5S7w:-KHZYREextGMkhWq5S7x:810495425) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/bower.json#L2)):_

> ``` JSON
> {
>   "name": "angular2-polymer-elements-quickstart",
> ```

Probably this is a very long name, I would vote angular2-polymer-quickstart

---

_[bower.json, line 8 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZYbUJr7-3TNvN22WL:-KHZYbUK8M-YUivW-v3_:690032133) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/bower.json#L8)):_

> ``` JSON
>     "Anton Platonov <platosha@gmail.com>"
>   ],
>   "license": "ISC",
> ```

Everything in vaadin uses to be Apache 2, and the project has an Apache LICENSE file

---

_[bower.json, line 16 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZYnmUAUGVV9kAoblG:-KHZYnmVgK8roYtJO4Kd:1996680637) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/bower.json#L16)):_

> ``` JSON
>     "bower_components",
>     "test",
>     "tests"
> ```

Remove tests, normally folder for testing is test

---

_[package.json, line 12 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZa9x8xUUGbmDiTOoW:-KHZa9x8xUUGbmDiTOoX:1620991667) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/package.json#L12)):_

> ``` JSON
>     "typings": "typings"
>   },
>   "license": "ISC",
> ```

Apache

---

_[README.md, line 1 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZZCuemGqVthlPAcsM:-KHZZCuemGqVthlPAcsN:-966784484) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/README.md#L1)):_

> ``` Markdown
> # angular2-polymer-elements-quickstart
> ```

I would elaborate a bit more this, like angular quick-start.
I miss how to clone the repo, remove the git history and initialise git again.
Also what is this project about, links to angular, polymer, ng2-polymer, polymer-elements and vaadin-elements

---

_[tsconfig.json, line 10 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZ_5VbQWua3aI1Rf_x:-KHZ_5VbQWua3aI1Rf_y:668097692) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/tsconfig.json#L10)):_

> ``` JSON
>     "experimentalDecorators": true,
>     "removeComments": false,
>     "noImplicitAny": false
> ```

set it to true since it's the default in angular quickstart

---

_[app/hero.ts, line 4 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZ_RINnjCIcoe9AO-7:-KHZ_RINnjCIcoe9AO-8:-1984353044) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/app/hero.ts#L4)):_

> ``` XML
>   id: number;
>   name: string;
>   birthday: string;
> ```

Why is it string, I think it should be a date

---

_[app/main.ts, line 10 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZ_lXLCcazdGnAVqfq:-KHZ_lXLCcazdGnAVqfr:1569754066) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/app/main.ts#L10)):_

> ``` XML
> Copyright 2016 Google Inc. All Rights Reserved.
> Use of this source code is governed by an MIT-style license that
> can be found in the LICENSE file at http://angular.io/license
> ```

Remove this copyright.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1)_

**Comment by manolo** [comment]
Review status: 2 of 15 files reviewed at latest revision, 9 unresolved discussions.

---

_[bower.json, line 6 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZb0226uys8w_VAnnS:-KHZb0226uys8w_VAnnT:1454689642) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/bower.json#L6)):_

> ``` JSON
>   "main": "",
>   "authors": [
>     "Anton Platonov <platosha@gmail.com>"
> ```

Use your vaadin email here, or just transfer owner to vaadin elements.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1)_

**Comment by Saulis** [comment]
Review status: 1 of 15 files reviewed at latest revision, 9 unresolved discussions.

---

_[bower.json, line 16 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZYnmUAUGVV9kAoblG:-KHZerOOHKXtU3DzhIwQ:1349276893) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/bower.json#L16)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Remove tests, normally folder for testing is test</details>
> Yes, normally we don't want to distribute tests when users install this package as a dependency so it's better to keep them ignored.

---

_[README.md, line 1 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZZCuemGqVthlPAcsM:-KHZfVB2-vJHUly5RPLP:-57334789) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/README.md#L1)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> I would elaborate a bit more this, like angular quick-start.
> I miss how to clone the repo, remove the git history and initialise git again.
> Also what is this project about, links to angular, polymer, ng2-polymer, polymer-elements and vaadin-elements</details>
> There's also https://github.com/vaadin/angular2-elements-examples – we might want to combine these two into one.

---

_[app/hero.ts, line 4 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZ_RINnjCIcoe9AO-7:-KHZflDfR2oolpL9XJAa:-1728496470) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/app/hero.ts#L4)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Why is it string, I think it should be a date</details>
> `value` in `<vaadin-date-picker>` uses Strings.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1)_

**Comment by platosha** [comment]
Review status: 1 of 15 files reviewed at latest revision, 9 unresolved discussions.

---

_[bower.json, line 2 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZYREextGMkhWq5S7w:-KHZhUFPQPZknmt3gIOQ:-1805638397) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/bower.json#L2)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Probably this is a very long name, I would vote angular2-polymer-quickstart</details>
> Alright. But then I’ve got to rename the repo, I'm afraid this could break the review. I'll better do it after merging this PR.

---

_[bower.json, line 6 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZb0226uys8w_VAnnS:-KHZgBE1dCJQXaW5ZT8t:-499146009) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/bower.json#L6)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Use your vaadin email here, or just transfer owner to vaadin elements.</details>
> Done.

---

_[bower.json, line 8 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZYbUJr7-3TNvN22WL:-KHZgCzKnJQWLvN4hA7R:-499146009) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/bower.json#L8)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Everything in vaadin uses to be Apache 2, and the project has an Apache LICENSE file</details>
> Done.

---

_[bower.json, line 16 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZYnmUAUGVV9kAoblG:-KHZgG2lq-lxlR8PtPKr:-499146009) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/bower.json#L16)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> Yes, normally we don't want to distribute tests when users install this package as a dependency so it's better to keep them ignored.</details>
> Done.

---

_[package.json, line 12 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZa9x8xUUGbmDiTOoW:-KHZgH_q_veRerpnkQwV:-499146009) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/package.json#L12)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Apache</details>
> Done.

---

_[README.md, line 1 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZZCuemGqVthlPAcsM:-KHZgLz6leYv0fGAVKyf:-1213228231) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/README.md#L1)):_
<details><summary>

<i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>



> There's also https://github.com/vaadin/angular2-elements-examples – we might want to combine these two into one.</details>
> Well, I don’t feel that someone else needs the examples app, except for us who build the examples.

I was going to write this README after the tutorial text, before publishing. The purpose of this review is to verify that the application is a good base to explain in the tutorial. The README is not part of the code in any way.

---

_[tsconfig.json, line 10 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZ_5VbQWua3aI1Rf_x:-KHZfMHjZO1j3dhTdnIp:2114064916) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/tsconfig.json#L10)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> set it to true since it's the default in angular quickstart</details>
> It’s false in the quickstart: https://angular.io/docs/ts/latest/quickstart.html

---

_[app/hero.ts, line 4 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZ_RINnjCIcoe9AO-7:-KHZcg13Box3Tjosg9dW:748130368) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/app/hero.ts#L4)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Why is it string, I think it should be a date</details>
> It is string to simplify binding with date picker's value.

`Date` type in JS is not good for storing only dates, because internally it's a DateTime-like type, which always stores some time.

Having this as `Date` would bring additional complexity for value conversion and timezone handling with no real benefits.

---

_[app/main.ts, line 10 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZ_lXLCcazdGnAVqfq:-KHZhp9eF6I-Z0-MjCbq:-499146009) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/app/main.ts#L10)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Remove this copyright.</details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1)_

**Comment by manolo** [comment]
Review status: 1 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

_[README.md, line 1 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZZCuemGqVthlPAcsM:-KHZoQQsTad1gQ4gBBo6:7392102) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/README.md#L1)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> Well, I don’t feel that someone else needs the examples app, except for us who build the examples.
> 
> I was going to write this README after the tutorial text, before publishing. The purpose of this review is to verify that the application is a good base to explain in the tutorial. The README is not part of the code in any way.</details>
> Ok, update the Readme in a separate PR

---

_[tsconfig.json, line 10 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZ_5VbQWua3aI1Rf_x:-KHZokoGy-vf00dwgz7k:-1664530428) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/tsconfig.json#L10)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> It’s false in the quickstart: https://angular.io/docs/ts/latest/quickstart.html</details>
> Seems true in : https://github.com/angular/quickstart/blob/master/tsconfig.json#L10

---

_[app/hero.ts, line 4 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZ_RINnjCIcoe9AO-7:-KHZoyZFFLsXl7r-OFHx:2016503024) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/app/hero.ts#L4)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> It is string to simplify binding with date picker's value.
> 
> `Date` type in JS is not good for storing only dates, because internally it's a DateTime-like type, which always stores some time.
> 
> Having this as `Date` would bring additional complexity for value conversion and timezone handling with no real benefits.</details>
> The thing is that any serious model would store dates as dates or ts. It looks like we are cheating here. Might be a comment saying '// Using strings for simplicity'

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1)_

**Comment by platosha** [comment]
Review status: 1 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

_[tsconfig.json, line 10 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZ_5VbQWua3aI1Rf_x:-KH_RGhbeYAPKigP7-Ac:-499146009) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/tsconfig.json#L10)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> Seems true in : https://github.com/angular/quickstart/blob/master/tsconfig.json#L10</details>
> Done.

---

_[app/hero.ts, line 4 [r1]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHZ_RINnjCIcoe9AO-7:-KH_RIke7LBWjpOem85L:-499146009) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/4f52930eb7efbbbad8e273ab3f3eed8e98a89ad2/app/hero.ts#L4)):_
<details><summary>

<i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>



> The thing is that any serious model would store dates as dates or ts. It looks like we are cheating here. Might be a comment saying '// Using strings for simplicity'</details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1)_

**Comment by tehapo** [comment]
Added two minor comments. Otherwise :lgtm: :+1: 

<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> #### Feature/mvp
> 
> Resolves vaadin/components-team-tasks#152
> 
> </details>

---

Reviewed 5 of 15 files at r1, 4 of 4 files at r2, 4 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_[index.html, line 10 [r4]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHcqYf9TYHQGKlk1pko:-KHcqYf9TYHQGKlk1pkp:-1440323294) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/5e5e0508fa9ac1653e62ed01327565534c97bfb2/index.html#L10)):_

> ``` HTML
> 
>     
>     <script src="bower_components/webcomponentsjs/webcomponents.min.js"></script>
> ```

Is there a reason not to use `webcomponents-lite.min.js`?

---

_[package.json, line 29 [r4]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHcqQ3eG8rcKjwn4SJD:-KHcqQ3eG8rcKjwn4SJE:1919787411) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/5e5e0508fa9ac1653e62ed01327565534c97bfb2/package.json#L29)):_

> ``` JSON
>     "zone.js": "^0.6.12",
> 
>     "@vaadin/angular2-polymer": "git+https://github.com/vaadin/angular2-polymer.git#feature/polymer-dom-adapter",
> ```

This could now be changed to:
`"@vaadin/angular2-polymer": "1.0.0-alpha2",`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-:-KHcqhq9Huo3uF7YDNgJ:-2133215352)_

**Comment by platosha** [comment]
Review status: 14 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

_[index.html, line 10 [r4]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHcqYf9TYHQGKlk1pko:-KHd0CRqSmt_u2bMMyQd:1269649921) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/5e5e0508fa9ac1653e62ed01327565534c97bfb2/index.html#L10)):_
<details><summary>

<i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>



> Is there a reason not to use `webcomponents-lite.min.js`?</details>
> Nope. Switched to the lite polyfill.

---

_[package.json, line 29 [r4]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHcqQ3eG8rcKjwn4SJD:-KHd0FsNAS3BvLF5egZB:-1880371561) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/5e5e0508fa9ac1653e62ed01327565534c97bfb2/package.json#L29)):_
<details><summary>

<i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>



> This could now be changed to:
> `"@vaadin/angular2-polymer": "1.0.0-alpha2",`</details>
> Unfortunately no. It still depends on PolymerDomAdapter branch, which is still not merged yet. Otherwise partly broken.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1)_

**Comment by tehapo** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[package.json, line 29 [r4]](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1#-KHcqQ3eG8rcKjwn4SJD:-KHd0zQym3bFXIf2VdW3:-1251683152) ([raw file](https://github.com/platosha/angular2-polymer-elements-quickstart/blob/5e5e0508fa9ac1653e62ed01327565534c97bfb2/package.json#L29)):_
<details><summary>

<i>Previously, platosha (Anton Platonov) wrote…</i></summary>



> Unfortunately no. It still depends on PolymerDomAdapter branch, which is still not merged yet. Otherwise partly broken.</details>
> Got it. :+1: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/platosha/angular2-polymer-elements-quickstart/1)_

**Pull request merged**
